name = "Kaktus"
license = "MIT"
licenselink = "https://github.com/abhijit-hota/kaktus/blob/master/LICENSE"
description = "A maintained, minimal and modern fork of Cactus theme for Hugo."
homepage = "https://github.com/abhijit-hota/kaktus"
demosite = ""
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.55"

# If the theme has a single author
[author]
name = "Abhijit Hota"
homepage = "https://abhijithota.me"

# If porting an existing theme
[original]
author = "Pieter Robberechts"
homepage = "https://github.com/probberechts"
repo = "https://github.com/probberechts/hexo-theme-cactus"
